name: Moadream Server CD

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Python 3.11
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'mock-api/requirements.txt'

      - name: Setup JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Install Python Dependencies
        run: |
          cd mock-api
          pip install -r requirements.txt

      - name: Run Black
        run: |
          cd mock-api
          black --check --diff .

      - name: Run Flake8
        run: |
          cd mock-api
          flake8 .

      - name: Run Mypy
        run: |
          cd mock-api
          mypy app.py
        continue-on-error: true

      - name: Run Python Tests
        run: |
          cd mock-api
          pytest --verbose

      - name: Run Spotless
        run: ./gradlew spotlessCheck

      - name: Run Java Tests
        run: ./gradlew test

  deploy:
    runs-on: ubuntu-latest
    environment: Deploy
    needs: test
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Remove existing application.yaml
        run: rm -f src/main/resources/application.yaml
        shell: bash

      - name: Remove existing application-deploy.yaml
        run: rm -f src/main/resources/application-deploy.yaml
        shell: bash

      - name: Create application-deploy.yaml
        run: |
          cat <<'EOF' > ./src/main/resources/application-deploy.yml
          ${{ secrets.DEPLOY_YML }}
          EOF
        shell: bash

      - name: Create .env.prod file
        run: |
          echo "${{ secrets.ENV_PROPERTIES }}" > .env.prod
        shell: bash

      - name: Build with Gradle
        run: ./gradlew --build-cache clean build -x test -x spotlessCheck

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/nextach/moadream-server:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to Server
        uses: 8G4B/GSM-SV-Deploy@v1.2.1
        with:
          host: ${{ secrets.SERVER_HOST }}
          target_path: /home/ubuntu/moadream-server
          user: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}